/**
 * scheduler.js
 *
 * Implements the Automated Reorder Workflow from Report Section 4.4.3:
 *
 * 1. Nightly job queries all products where total_stock <= reorder_level
 * 2. For each under-stocked product, retrieves preferred supplier
 * 3. Groups items by supplier → generates one draft PO per supplier
 * 4. Logs summary (email integration point documented inline)
 *
 * Runs automatically when NODE_ENV !== 'test'.
 * Can also be triggered manually via POST /api/v1/stock/trigger-reorder (admin only).
 */

const { sequelize }   = require('../config/database');
const { PurchaseOrder, POItem } = require('../models');
const logger          = require('./logger');

// ─── Simple interval-based scheduler (no external dependency needed) ──────────
// For production, replace with node-cron: `0 2 * * *` (2am nightly)
const INTERVAL_MS = 24 * 60 * 60 * 1000; // 24 hours

/**
 * Core reorder logic — can be called directly or by the interval.
 * Returns a summary of what was generated.
 */
const runReorderCheck = async () => {
  logger.info('⏰  Reorder check started…');

  const [lowStockItems] = await sequelize.query(`
    SELECT
      p.product_id,
      p.name        AS product_name,
      p.sku,
      p.reorder_qty,
      p.reorder_level,
      COALESCE(SUM(s.qty_on_hand), 0) AS total_stock,
      ps.supplier_id,
      ps.unit_cost,
      ps.supplier_sku,
      sup.company_name AS supplier_name,
      -- Use warehouse with lowest stock as receiving location (fallback to warehouse_id=1)
      COALESCE(
        (SELECT warehouse_id FROM stock
         WHERE product_id = p.product_id
         ORDER BY qty_on_hand ASC LIMIT 1),
        1
      ) AS target_warehouse_id
    FROM   product p
    LEFT   JOIN stock    s  ON p.product_id  = s.product_id
    LEFT   JOIN product_supplier ps ON p.product_id = ps.product_id AND ps.is_preferred = 1
    LEFT   JOIN supplier sup ON ps.supplier_id = sup.supplier_id
    WHERE  p.is_active = 1
      AND  ps.supplier_id IS NOT NULL
    GROUP  BY p.product_id, p.name, p.sku, p.reorder_qty, p.reorder_level,
              ps.supplier_id, ps.unit_cost, ps.supplier_sku, sup.company_name
    HAVING total_stock <= p.reorder_level
    ORDER  BY ps.supplier_id
  `);

  if (lowStockItems.length === 0) {
    logger.info('✅  Reorder check: all stock levels are adequate');
    return { generated: 0, items_covered: 0 };
  }

  logger.info(`⚠️   Found ${lowStockItems.length} under-stocked product(s) — generating draft POs…`);

  // Group by supplier_id
  const bySupplier = {};
  for (const item of lowStockItems) {
    if (!bySupplier[item.supplier_id]) {
      bySupplier[item.supplier_id] = {
        supplier_id:   item.supplier_id,
        supplier_name: item.supplier_name,
        items:         [],
      };
    }
    bySupplier[item.supplier_id].items.push(item);
  }

  let posGenerated = 0;

  await sequelize.transaction(async (t) => {
    for (const [supplierId, group] of Object.entries(bySupplier)) {
      // Calculate total amount for this PO
      const totalAmount = group.items.reduce(
        (sum, i) => sum + parseFloat(i.unit_cost || 0) * parseInt(i.reorder_qty),
        0
      );

      // Create draft PO
      const po = await PurchaseOrder.create({
        supplier_id:   parseInt(supplierId),
        status:        'draft',
        total_amount:  totalAmount,
        notes:         `Auto-generated by reorder scheduler on ${new Date().toISOString().slice(0,10)}`,
        created_by:    null, // System-generated
      }, { transaction: t });

      // Create PO items
      for (const item of group.items) {
        await POItem.create({
          po_id:        po.po_id,
          product_id:   item.product_id,
          warehouse_id: item.target_warehouse_id,
          qty_ordered:  parseInt(item.reorder_qty),
          unit_cost:    parseFloat(item.unit_cost || 0),
          qty_received: 0,
        }, { transaction: t });
      }

      posGenerated++;

      logger.info(
        `📋  Draft PO #${po.po_id} created for ${group.supplier_name} — ` +
        `${group.items.length} item(s), total: ${totalAmount.toFixed(2)}`
      );

      // ── Email notification hook ──────────────────────────────────────────
      // In production, send email to procurement manager here.
      // Example with nodemailer (install separately):
      //
      // await emailService.send({
      //   to:      process.env.PROCUREMENT_EMAIL,
      //   subject: `[IMS] Reorder PO #${po.po_id} requires approval`,
      //   body:    `${group.items.length} items from ${group.supplier_name} need reordering.`
      // });
    }
  });

  const summary = {
    generated:     posGenerated,
    items_covered: lowStockItems.length,
    suppliers:     Object.keys(bySupplier).length,
  };

  logger.info(`✅  Reorder check complete: ${posGenerated} PO(s) generated for ${lowStockItems.length} item(s)`);
  return summary;
};

/**
 * Start the scheduler.
 * Called once from server.js after DB connects.
 */
const startScheduler = () => {
  if (process.env.NODE_ENV === 'test') return;

  logger.info('⏰  Reorder scheduler initialised (runs every 24h)');

  // Run once shortly after startup (after 30s to let DB warm up)
  setTimeout(async () => {
    try { await runReorderCheck(); }
    catch (err) { logger.error('Reorder check failed on startup run:', err.message); }
  }, 30_000);

  // Then run every 24 hours
  setInterval(async () => {
    try { await runReorderCheck(); }
    catch (err) { logger.error('Reorder check failed on scheduled run:', err.message); }
  }, INTERVAL_MS);
};

module.exports = { startScheduler, runReorderCheck };
